version: "3.7"
services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: app
        container_name: app_container
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - texnomart
    db:
        image: mysql:8.0
        container_name: db_container
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: texnomart
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - texnomart
    nginx:
        image: nginx:alpine
        container_name: nginx_container
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - texnomart
networks:
  texnomart:
      driver: bridge
